---
- hosts: clowderserver
  sudo: yes
  pre_tasks:
    - apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
    - apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present
#    - apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
#    - apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

#   This package should usually be supplied in the base image, vivid requires a reboot after it is installed.
#    - apt: pkg=policykit-1 state=installed

    - name: Install Packages
      apt: pkg={{ item }} state=installed update_cache=yes
      with_items:
        - openjdk-7-jdk
        - mongodb
        - rabbitmq-server
        - unzip
        - postfix
        - git

    - file: path=/etc/rabbitmq/rabbitmq.conf.d state=directory
    - command: rabbitmq-plugins enable rabbitmq_management

    - user: name=clowder system=yes group=users state=present

    - name: Install Clowder Distribution (built locally with 'dist')
      unarchive: copy=yes src=../clowder/target/universal/clowder-0.9.1-SNAPSHOT.zip dest=/home/clowder owner=clowder group=users creates=/home/clowder/clowder-0.9.1-SNAPSHOT/conf/application.conf

    - name: Configure Clowder
      file: path=/home/clowder/clowder-0.9.1-SNAPSHOT/custom state=directory owner=clowder group=users
    - lineinfile: dest=/home/clowder/clowder-0.9.1-SNAPSHOT/conf/play.plugins regexp="^9992:services.RabbitmqPlugin" insertafter="^#9992:services.RabbitmqPlugin" line="9992:services.RabbitmqPlugin"
    - lineinfile: dest=/home/clowder/clowder-0.9.1-SNAPSHOT/conf/application.conf regexp="^application.secret=" line="application.secret=\"{{ application_secret }}\""

    - name: Enable services
      service: name={{ item }} enabled=yes
      with_items:
        - mongodb
        - rabbitmq-server
      notify: restart services

    - command: rabbitmqctl add_user {{ rabbitmq_username }} {{ rabbitmq_password }}
    - command: rabbitmqctl set_permissions {{ rabbitmq_username }} ".*" ".*" ".*"

  roles:
    - pyclowder
    - extractors-siegfried

  handlers:
    - name: restart services
      service: name={{ item }} state=restarted
      with_items:
        - mongodb
        - rabbitmq-server
